SumoLogic/sumologic-kubernetes-collection-helm-operator

Dockerfile
config/manager/manager.yaml
tests/test.sh

Summary of changes:
- update base image to helm operator 1.7.1
- update packages in container image
- update Helm operator image in tests
- update Helm operator image in templates

Update helm operator image

---

Makefile
bundle.Dockerfile
bundle/manifests/helm-operator.sumologic.com_sumologiccollections.yaml
bundle/manifests/operator.clusterserviceversion.yaml
bundle/manifests/sumologic-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/sumologic-controller-manager_v1_serviceaccount.yaml
bundle/manifests/sumologic-manager-config_v1_configmap.yaml
bundle/manifests/sumologic-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
config/manifests/bases/operator.clusterserviceversion.yaml
config/samples/default_openshift.yaml

Image: `ghcr.io/kkujawa-sumo/sumologic-kubernetes-collection-helm-operator-bundle:0.0.6`

Add bundle for Operator Hub

---

bundle.yaml
bundle/manifests/operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
config/public_images/manager_auth_proxy_patch.yaml

this is the name of Configmap which is used in leader election

operator: set leader-election-id to more meaningful

---

Makefile
config/manager/manager.yaml
tests/check_bundle_status.sh

following command is used in Makefile to change image:
`kustomize edit set image controller="${IMG}"`

operator: fix setting operator image in templates

---

.github/workflows/dev_builds.yaml
.github/workflows/release_builds.yaml

add step to checkout submodule
change the type of parentheses for variables
Previous status of github action: https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/runs/2638952647

ci: fix building and pushing of container images

---

.github/workflows/dev_builds.yaml
.github/workflows/release_builds.yaml

ci: fix building of container images

---

.github/workflows/pull_requests.yml

Changes in k3d-action 1.5.0: https://github.com/AbsaOSS/k3d-action/releases/tag/v1.5.0
Related to https://github.com/SumoLogic/tailing-sidecar/issues/179

chore: update k3d-action to 1.5.0

---

config/samples/default_openshift.yaml
config/samples/receiver_mock_openshift.yaml

Set UBI based images for Fluent Bit and Tailing Sidecar Operator

Set UBI based images for Fluent Bit and Tailing Sidecar Operator

---

config/samples/default_openshift.yaml
config/samples/receiver_mock_openshift.yaml

added to configuration:
- public.ecr.aws/sumologic/kubernetes-fluentd:1.12.2-sumo-0-ubi
- public.ecr.aws/sumologic/sumo-ubi-minimal:8.4

feat(samples/openshift): use ubi images

---

Makefile
bundle.yaml
bundle/manifests/operator.clusterserviceversion.yaml
tests/deploy_helm_operator.sh

changes between 2.1.4-0-rc.1 and 2.1.4-0-rc.2: https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/compare/f61e56eeaecac1550ae3e12a79e9114bac6e7246..87b37b764857e2f1244f903d424fbc62513f2258

release: prepare 2.1.4-0-rc.2

---

Makefile
bundle.yaml
bundle/manifests/operator.clusterserviceversion.yaml
tests/deploy_helm_operator.sh

Changes between 2.1.4-0-rc.2 and 2.1.4-0-rc.3: https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/compare/87b37b764857e2f1244f903d424fbc62513f2258..9feeaa72f1b43086a13417ee54c27bf91cab7e68

release: prepare 2.1.4-0-rc.3

---

.github/workflows/release_builds.yaml

related failure of github action:
https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/actions/runs/2796976573

fix(ci): add missing LATEST_TAG env

---

.github/workflows/release_builds.yaml

related failure of github action: https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/runs/7674877753?check_suite_focus=true

fix(ci): define BUNDLE_IMAGE_NAME env explicitly

---

.github/workflows/pull_requests.yml
Dockerfile
Makefile
bundle/manifests/operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
tests/compare_manifests.sh
tests/deploy_helm_chart.sh
tests/deploy_helm_operator.sh
tests/functions.sh
tests/test_openshift.yaml
vagrant/provision.sh

Changes between Sumologic Kubernetes Collection Helm Chart v2.17.0 and v2.19.1: https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/v2.17.0...v2.19.1

chore: update Sumologic Kubernetes Collection Helm Chart to v2.19.1

---

bundle.yaml
bundle/manifests/operator.clusterserviceversion.yaml
config/manager/manager.yaml
tests/deploy_helm_operator.sh

chore: update kubernetes-setup image to v3.4.0-ubi-2

---

tests/deploy_helm_chart.sh
tests/test_openshift.yaml

unset env
```
manager:
env:
```
caused following problem in helm operator:
```
{"level":"error","ts":"2023-09-04T12:06:34Z","logger":"helm.controller","msg":"Release failed","namespace":"sumologic-system","name":"test-openshift","apiVersion":"helm-operator.sumologic.com/v1alpha1","kind":"SumologicCollection","release":"test-openshift","error":"failed to install release: values don't meet the specifications of the schema(s) in the following chart(s):\nopentelemetry-operator:\n- manager: env is required\n","stacktrace":"github.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\t/workspace/internal/helm/controller/reconcile.go:243\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-r …
```

chore: enable Helm Operator in tests

---

config/samples/full_config.yaml
tests/test_openshift.yaml

https://kubernetes.io/blog/2023/03/10/image-registry-redirect/

chore: change k8s.gcr.io registry to registry.k8s.io

---

config/samples/default_openshift_4_12.yaml

this configuration uses recommendation from: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1742#issuecomment-1272904626

chore: add example configuration for OpenShift 4.12

---

.github/workflows/dev_builds.yaml
.github/workflows/pull_requests.yml
.github/workflows/release_builds.yaml
Makefile
scripts/generate_watches.py
scripts/get_image_config_keys.py
scripts/update_images.py
vagrant/provision.sh

Related to https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/pull/118#pullrequestreview-2129935168
Summary of changes:
- chore: add python formatter
- chore: update ubuntu to 22.04 in github action workflows to have compatible black versions in Vagrant and github actions

chore: add python formatter - black

---

bundle/manifests/operator.clusterserviceversion.yaml

add permissions from https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/pull/123/commits/9f34da99f6b7ed2c829f46a19421f8872fea1432

fix: adjust ClusterRole to new version of the Helm Chart

---

.github/workflows/dev_builds.yaml
.github/workflows/release_builds.yaml
Makefile

Release notes for OPM v1.45.0: https://github.com/operator-framework/operator-registry/releases/tag/v1.45.0

chore: update Operator Package Manager (opm)
